export const CREATE_TRANSACTION = "CREATE_TRANSACTION"
export const SAVE_TRANSACTION = "SAVE_TRANSACTION"
export const CANCEL_TRANSACTION = "CANCEL_TRANSACTION"

export const SET_QUANTITY = "SET_QUANTITY"

export const CLOSE_TRANSACTION_ALERT = "CLOSE_TRANSACTION_ALERT"
